import { ImageSourcePropType } from 'react-native';

const images: { [key: string]: ImageSourcePropType } = {
  Onboarding: require('../Images/Onboarding.png'),
  Logo: require('../Images/Logo.png'),
  Background: require('../Images/Background.png'),
  googleIcon: require('../Images/googleIcon.png'),
  appleIcon: require('../Images/appleIcon.png'),
  continue: require('../Images/continue.png'),
  backIcon: require('../Images/backIcon.png'),
  profile: require('../Images/profile.png'),
  camera: require('../Images/camera.png'),
  arrowdown: require('../Images/arrowdown.png'),
  success: require('../Images/success.png'),
  drawerIcon: require('../Images/drawerIcon.png'),
  bell: require('../Images/bell.png'),
  headerprofile: require('../Images/headerprofile.png'),
  slider1: require('../Images/slider1.png'),
  product1: require('../Images/product1.png'),
  slider2: require('../Images/slider2.png'),
  slider3: require('../Images/slider3.png'),
  product2: require('../Images/product2.png'),
  product3: require('../Images/product3.png'),
  product4: require('../Images/product4.png'),
  product5: require('../Images/product5.png'),
  product6: require('../Images/product6.png'),
  homeIcon: require('../Images/homeIcon.png'),
  bottomTabSecIcon: require('../Images/bottomTabSecIcon.png'),
  Favorite: require('../Images/Favorite.png'),
  profileIcon: require('../Images/profileIcon.png'),
  profileImage: require('../Images/profileImage.png'),
  homeslider: require('../Images/homeslider.png'),
  Bin: require('../Images/Bin.png'),
  pakistan: require('../Images/pakistan.png'),
  khadi: require('../Images/khadi.png'),
  searchbar: require('../Images/searchbar.png'),
  Heart: require('../Images/Heart.png'),
  Heel: require('../Images/Heel.png'),
  Bag: require('../Images/Bag.png'),
  Remove: require('../Images/Remove.png'),
  plus: require('../Images/plus.png'),
  Checkout: require('../Images/Checkout.png'),
  GetHelp: require('../Images/GetHelp.png'),
  email: require('../Images/email.png'),
  calender: require('../Images/calender.png'),
  Stars: require('../Images/Stars.png'),
  map: require('../Images/map.png'),
  HeartFilled: require('../Images/HeartFilled.png'),
  cartIcon: require('../Images/cartIcon.png'),
  Confirmed: require('../Images/Confirmed.png'),
  preparing: require('../Images/preparing.png'),
  Completed: require('../Images/Completed.png'),
  notification: require('../Images/notification.png'),
  Logout: require('../Images/Logout.png'),
};

export default images;
